# Generated by Django 5.2 on 2025-11-11 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Transform Your Future with Expert-Led Online Courses",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Join thousands of successful learners who have advanced their careers through our comprehensive online education platform."
                    ),
                ),
                (
                    "feature_1",
                    models.CharField(
                        default="20+ Expert instructors with industry experience",
                        max_length=200,
                    ),
                ),
                (
                    "feature_2",
                    models.CharField(
                        default="Certificate of completion for every course",
                        max_length=200,
                    ),
                ),
                (
                    "feature_3",
                    models.CharField(
                        default="24/7 access to course materials and resources",
                        max_length=200,
                    ),
                ),
                (
                    "feature_4",
                    models.CharField(
                        default="Interactive assignments and real-world projects",
                        max_length=200,
                    ),
                ),
                (
                    "cta_students_count",
                    models.IntegerField(
                        default=15000, help_text="Students enrolled for CTA section"
                    ),
                ),
                (
                    "cta_courses_count",
                    models.IntegerField(
                        default=150, help_text="Courses available for CTA section"
                    ),
                ),
                (
                    "cta_success_rate",
                    models.IntegerField(
                        default=98, help_text="Success rate for CTA section"
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Browse Courses", max_length=50),
                ),
                (
                    "cta_button_url",
                    models.CharField(default="courses.html", max_length=200),
                ),
                (
                    "secondary_button_text",
                    models.CharField(default="Enroll Now", max_length=50),
                ),
                (
                    "secondary_button_url",
                    models.CharField(default="enroll.html", max_length=200),
                ),
                (
                    "cta_image",
                    models.ImageField(blank=True, null=True, upload_to="cta_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page CTA",
                "verbose_name_plural": "Home Page CTAs",
            },
        ),
        migrations.CreateModel(
            name="HomePageFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome or Bootstrap icon class (e.g., 'fas fa-laptop-code', 'bi bi-shield-check')",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Home Page Feature",
                "verbose_name_plural": "Home Page Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageFloatingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        choices=[
                            ("bi bi-code-slash", "Code Slash"),
                            ("bi bi-palette", "Palette"),
                            ("bi bi-graph-up", "Graph Up"),
                            ("bi bi-layers", "Layers"),
                            ("bi bi-gem", "Gem"),
                        ],
                        default="bi bi-code-slash",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Course category/title", max_length=100),
                ),
                (
                    "student_count",
                    models.IntegerField(
                        default=0, help_text="Number of students for this category"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Home Page Floating Card",
                "verbose_name_plural": "Home Page Floating Cards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Transform Your Future with Expert-Led Online Courses",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Discover thousands of high-quality courses designed by industry professionals. Learn at your own pace, gain in-demand skills, and advance your career from anywhere in the world."
                    ),
                ),
                (
                    "students_count",
                    models.IntegerField(
                        default=50000, help_text="Number of students enrolled"
                    ),
                ),
                (
                    "courses_count",
                    models.IntegerField(
                        default=1200, help_text="Number of expert courses"
                    ),
                ),
                (
                    "success_rate",
                    models.IntegerField(
                        default=98, help_text="Success rate percentage"
                    ),
                ),
                (
                    "feature_1_title",
                    models.CharField(default="Certified Programs", max_length=100),
                ),
                (
                    "feature_2_title",
                    models.CharField(default="Lifetime Access", max_length=100),
                ),
                (
                    "feature_3_title",
                    models.CharField(default="Expert Instructors", max_length=100),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page Hero",
                "verbose_name_plural": "Home Page Heroes",
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="instructor_profiles/"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("course_count", models.IntegerField(default=0)),
                ("student_count", models.IntegerField(default=0)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("dribbble_url", models.URLField(blank=True)),
                ("behance_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Instructor",
                "verbose_name_plural": "Featured Instructors",
                "ordering": ["order"],
            },
        ),
    ]
